INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 1, 'A', '100', 30, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 2, 'A', '101', 35, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 3, 'A', '102', 30, 0, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 4, 'A', '200', 30, 0, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 5, 'A', '201', 15, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 6, 'A', '202', 15, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 7, 'B', '100', 30, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 8, 'B', '101', 35, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 9, 'B', '102', 30, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 10, 'B', '200', 30, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 11, 'B', '201', 15, 0, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 12, 'B', '202', 15, 0, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 13, 'C', '100', 30, 0, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 14, 'C', '101', 35, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 15, 'C', '102', 30, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 16, 'C', '200', 30, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 17, 'C', '201', 20, 1, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 18, 'C', '202', 15, 1, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 19, 'D', '100', 30, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 20, 'D', '101', 35, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 21, 'D', '102', 30, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 22, 'D', '200', 30, 0, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 23, 'D', '201', 15, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 24, 'D', '202', 15, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 25, 'H', '100', 30, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 26, 'H', '101', 35, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 27, 'H', '102', 30, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 28, 'H', '200', 30, 2, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 29, 'H', '201', 15, 0, 15);
INSERT INTO ROOM(id, building, number, capacity, type, changeover_time) VALUES ( 30, 'H', '202', 15, 0, 15);

INSERT INTO LECTURER(id, gender, title, name, changeover_time) VALUES ( 1, 'MALE', 'Prof. Dr. Dr. hc' ,'Hans Meier', 15);
INSERT INTO LECTURER(id, gender, title, name, changeover_time) VALUES ( 2, 'FEMALE', 'Prof. Dr.' ,'Maria Meier', 15);
INSERT INTO LECTURER(id, gender, title, name, changeover_time) VALUES ( 3, 'MALE', 'Dr.' ,'Martin Müller', 15);
INSERT INTO LECTURER(id, gender, title, name, changeover_time) VALUES ( 4, 'FEMALE', 'Dr.' ,'Martina Meyer', 15);
INSERT INTO LECTURER(id, gender, title, name, changeover_time) VALUES ( 5, 'MALE', 'Prof.' ,'Ulf Schmidt', 15);
INSERT INTO LECTURER(id, gender, title, name, changeover_time) VALUES ( 6, 'FEMALE', 'Professor' ,'Ursula Schröder', 15);
INSERT INTO LECTURER(id, gender, title, name, changeover_time) VALUES ( 7, 'MALE', 'Dipl.-Ing.' ,'Peter Zwackelmann', 15);
INSERT INTO LECTURER(id, gender, title, name, changeover_time) VALUES ( 8, 'FEMALE', 'Dipl.-Ökonomin' ,'Petra Pasetti', 15);
INSERT INTO LECTURER(id, gender, title, name, changeover_time) VALUES ( 9, 'MALE', 'Master Of Science' ,'Frank Stein', 15);
INSERT INTO LECTURER(id, gender, title, name, changeover_time) VALUES ( 10, 'FEMALE', 'Doktor' ,'Anna Rentner', 15);
INSERT INTO LECTURER(id, gender, title, name, changeover_time) VALUES ( 11, 'MALE', 'Dr.' ,'Bela Acula', 15);

INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 1 ,'A', 14, 'A', 25, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 2 ,'B', 11, 'A', 26, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 3 ,'B', 11, 'B', 34, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 4 ,'B', 11, 'C', 27, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 5 ,'B', 12, 'A', 27, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 6 ,'B', 12, 'B', 28, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 7 ,'B', 12, 'C', 31, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 8 ,'B', 13, 'A', 31, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 9 ,'B', 13, 'B', 32, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 10 ,'B', 13, 'C', 29, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 11 ,'I', 11, 'A', 26, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 12 ,'I', 11, 'B', 27, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 13 ,'I', 11, 'C', 25, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 14 ,'I', 12, 'A', 23, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 15 ,'I', 12, 'B', 27, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 16 ,'I', 12, 'C', 24, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 17 ,'I', 13, 'A', 23, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 18 ,'I', 13, 'B', 24, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 19 ,'I', 13, 'C', 25, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 20 ,'W', 11, 'A', 31, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 21 ,'W', 11, 'B', 32, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 22 ,'W', 11, 'C', 28, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 23 ,'W', 12, 'A', 23, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 24 ,'W', 12, 'B', 25, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 25 ,'W', 12, 'C', 26, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 26 ,'W', 13, 'A', 24, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 27 ,'W', 13, 'B', 26, 15);
INSERT INTO CENTURY(id, major, year, centuryChar, size, changeover_time) VALUES ( 28 ,'W', 13, 'C', 25, 15);